algoritmo "Exercicio 3 (Aula5)"

var
    n, fator, faton : inteiro
inicio
      escreval("Informe um número: ")
      leia (n)
      escreval(" ")
      escreval("----FATORIAL----")
      escreval(" ")
      fator <- n
      para fat de n ate 1 passo -1 faca
      escreval(fator)
      escreval("--------")
      faton <- fator * (fator - 1)
      escreval (fator, " *", fator - 1, " = ", faton)
      fimpara
      //João Paulo Theodoro Sampaio
      //João vitor Leite


fimalgoritmo
