algoritmo "Exercicio 1 (Aula5)"

var
   numero, numeromax, soma: inteiro
inicio
      escreval(" valor maior que 1: ")
      leia(nmax)
      para numero de 1 ate numeromax faca
      se (numero mod 2 = 0) entao
      soma <- soma + numero
      escreval("Numero Par: ", numero)
      senao
           escreval("Numero Impar", numero)
      fimse
      fimpara
      escreval("Soma dos numeros pares: ", soma)

      //João Paulo Theodoro Sampaio
      //João Vitor Leite

fimalgoritmo
